### ISSUE TITLE
problem with launch.json

### ISSUE THREAD

**Issue by CodingThinking** [DonJayamanne/pythonVSCode#1006]
## Environment data
VS Code version:  1.13.0
Python Extension version:  0.6.4
Python Version:   3.6
OS and version:    win10 1703

## Steps to reproduce:  
-  
-  

## Settings  
 {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "$python.pythonPath}",
            "program": "$}",
            "cwd": "$}",
            "env": {},
            "envFile": "$}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        }

I just update the vscode, and I start a new python script. Then I add a new item in launch.json and it becomes the one I copy above. So, is it a bug, or I have not got the point to use the extension? The extension worked well in vscode version 1.12

**Comment by jorwoods** [comment]
# Environment Data
* VS Code version = 1.13.0
* Python Extension version = 0.6.4
* Python Version = 3.5
* OS and version = win10 home

# Actual Behavior
Trying to launch using the django configuration below returns an error that manage.py does not exist when it definitely does. Worked as expected prior to updating to 1.13.0 and 0.6.4.

# Expected behavior
Runs django without error

# Steps to reproduce
* Update Visual Studio Code to 1.13.0
* Update Python Extension to 0.6.4.
* Run django application

# Settings


I am having a similar issue. I updated VSCode and the python extension, suddenly my launch.json changed from :
### Old and used to work 
`{
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "args": [
                "runserver",
                "--noreload"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
`
to
### New and doesn't work.
`{
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "$python.pythonPath}",
            "program": "$/manage.py",
            "cwd": "$}",
            "args": [
                "runserver",
                "--noreload"
            ],
            "env": {},
            "envFile": "$}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },`

Even changing the launch.json config options back to what used to work does not fix the problem.

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/DonJayamanne/pythonVSCode/commit/2e50f0f48937b7e1cf016ea76794dcb47dd3cae5

New build will be released shortly.

**Comment by jorwoods** [comment]
2e50f0f references Spark... Will this also fix the django launcher?

**Comment by CodingThinking** [comment]
Confirm resolved.
