### ISSUE TITLE
Change debugger to support the new json protocol implemented in PTVSD 

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#1018]
This is a big an critical change, affects almost all remote debugging instances.
As a temporary solution please use PTVSD version 3.0 until this extension is updated to support the latest version of PTVSD package.

https://github.com/DonJayamanne/pythonVSCode/issues/1011
https://github.com/DonJayamanne/pythonVSCode/issues/805
https://github.com/DonJayamanne/pythonVSCode/issues/999
https://github.com/DonJayamanne/pythonVSCode/issues/981

**Comment by DonJayamanne** [comment]
@zooba Version 3.0 of PTVSD python library has some significant changes. My extension still uses the old mechanism of communication, using the binary messages. Version 3.0 uses IPC JSON.

Looking at the .NET and the Python code in PTVS, I can see some members in code containing the words "Legacy". This seems to indicate that there's some backwards compatibility or the like. Is that correct?

Is it possible for me to use the new PTVSD 3.0 library using purely IPC JSON.

**Comment by zooba** [comment]
Our long-term plan is to make ptvsd's messages match VS Code, so that any shim should be very minimal. (And we want to enlist your help in this too :) )

Right now we needed to get off the binary protocol for security reasons, so we did a direct transformation into JSON and prefixed the messages with "legacy" so they don't collide with the new messages. Eventually we'll release ptvsd 4.0 that will be the start of our "fully compatible" guarantee - no breaking changes to the protocol, full compatibility with VS and VS Code extensions (of a certain version or later), and safe extensibility so we can enable things like remote REPL through the same library.

For now, I'd say your best solution is to simply document that the ptvsd version should be restricted for use with VS Code. We'd rather have your help directly on making ptvsd more compatible with VSC than making VSC more compatible with our in-transition ptvsd - we're currently working on making it easier to develop.

**Comment by DonJayamanne** [comment]
@zooba Thanks, I'll wait for version 4. In the mean time I'll inform those facing issues to use version 3.

If possible I'll try to check whether the version can be detected from the client, this way a more meaningful error can be displayed to the user. Thanks again.

**Comment by Dlizzz** [comment]
I do confirm that with "ptvsd==3.0.0" remote debugging is working.

VS Code version: 1.13.1 on Windows
Python Extension version: 0.6.5 on Windows
tpvsd version: 3.0.0 on Ubuntu
OS and version: Client on Windows 10 Professional 1703 - Server on Ubuntu Zesty 17.04

**Comment by AwayQuEM** [comment]
I still got `'Debug adapter process has terminated unexpectedly'` with `ptvsd==3.0.0`.

VS Code version: `1.13.1` on Mac 
Python Extension version: `0.6.5` on Mac
ptvsd version:`3.0.0` on Mac
OS version: OS X `10.12.5`
Python version: `3.5.2`

**Comment by AwayQuEM** [comment]
I also try to use ubuntu as client but still got  '`Debug adapter process has terminated unexpectedly`' with ptvsd==3.0.0.

VS Code version: 1.13.1 on Ubuntu
Python Extension version: 0.6.5 on Ubuntu
ptvsd version:3.0.0 on Ubuntu
OS version: Ubuntu 16.04
Python version: 3.5.2

**Comment by AwayQuEM** [comment]
I also try to use ubuntu as client but still got  '`Debug adapter process has terminated unexpectedly`' with ptvsd==3.0.0.

VS Code version: `1.13.1` on Ubuntu
Python Extension version: `0.6.5` on Ubuntu
ptvsd version:`3.0.0` on Ubuntu
OS version: Ubuntu `16.04`
Python version: `3.5.2`

I also tried python 2.7.10.

**Comment by DonJayamanne** [comment]
Please create a separate issue
