### ISSUE TITLE
Display currently selected interpreter in status bar (with option to select another)

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#1147]
Status bar entry showing what interpreter you have set.
Ff VS Code can’t find an interpreter then Jedi won’t even run and you might not notice this fact since you still get the in-file word completion, just not intellisense
Clicking this status bar will display existing prompt to select interpreter.

Will probably need to come up with a way to abbreviate what interpreters are available rather than listing the full path (e.g. version, CPython vs Anaconda vs PyPy, etc.)

**Comment by DonJayamanne** [comment]
@gandhis1, @brettcannon , @zooba

Looking for some feedback on the following UI. I'm displaying the (file) name of the Python interpreter suffixed with ```[Environment]```
Clicking on this will display the existing list to select an interpreter/environment.

![image](https://user-images.githubusercontent.com/1948812/30447537-42ddfe9a-9941-11e7-8e0f-9379ae57cd1e.png)

**Comment by zooba** [comment]
What about just displaying the last directory segment and the filename? I think it's clear enough from context what it means, yeah.

For example: "Anaconda3/python.exe" or "p27/.../python.exe" (you'll have to special case "Scripts" and probably "bin", but I doubt these add any valuable information anyway)

**Comment by gandhis1** [comment]
I agree with Zooba, that would be more informative

**Comment by DonJayamanne** [comment]
Suffix with "(vevn)" or "(virtualenv)", indicating whether it is a virtual env.
If it is a vevn, if this directory contains pyvenv.cfg.
Similarly find a way to identify virtualenv environments.

**Comment by zooba** [comment]
The most reliable way to identify virtualenv environments currently is to look for `..\Lib\orig-prefix.txt` (assuming you don't want to actually run the interpreter to ask it).

**Comment by brettcannon** [comment]
Another way to handle paths that is short is to do something like what zsh does and only use the first letter of the path parts, e.g. `/usr/local/bin/python3.6` would be `/u/l/bin/python3.6`.

As for `(venv)`/`(virtualenv)`, I do like that. That might do away with having to special case `Scripts/` and `bin/` if you give the virtualized interpreter's path as the suffix of e.g. `(venv)` will indicate that you're in a virtual environment.

Or what about saying the Python version instead of the executable name? The chances of people having multiple installations of the same major.minor.micro version is very small, and differentiating between a venv/virtualenv/conda environment and a system-level install will be handled by the parenthesized suffix. IOW, if the status bar said `Python 3.6.1 (venv)` it's very obvious what you're using, and `Python 3.6.1` shouldn't be confusing either unless you have both a CPython and Anaconda install and that's probably not common enough to worry about (the hover as @DonJayamanne showed will take care of that ambiguity).

And just while I'm thinking about it, does clicking on the status bar pop up the selection list?

**Comment by DonJayamanne** [comment]
@brettcannon
> And just while I'm thinking about it, does clicking on the status bar pop up the selection list?

Yes

**Comment by DonJayamanne** [comment]
## Picker on Linux (with Anaconda installed)
![picker on linux](https://user-images.githubusercontent.com/1948812/30620056-e38828d8-9d57-11e7-916b-dce1a8ebf98b.png)
## Picker on Windows (with Anaconda installed)
![picker on windows](https://user-images.githubusercontent.com/1948812/30620055-e385ec26-9d57-11e7-9459-0b95a4748b59.png)

## Linux status bar when Anaconda is selected
![statusbar conda](https://user-images.githubusercontent.com/1948812/30620057-e39cc928-9d57-11e7-8a78-a7ec02e2fb93.png)

## Windows status bar when Anaconda is selected
![statusbar conda windows](https://user-images.githubusercontent.com/1948812/30620129-439a2e9c-9d58-11e7-966f-dfff08b84c20.png)

## Invalid interpreter selected (warning icon)
![statusbar invalid interpreter](https://user-images.githubusercontent.com/1948812/30620052-e384233c-9d57-11e7-9d0d-f0fd813c45ef.png)

## Window Python 2.7 selected
![statusbar standard python interpreter](https://user-images.githubusercontent.com/1948812/30620053-e3844baa-9d57-11e7-8990-64018bf46aee.png)

## Virtual Environment selected
![statusbar virtual environment](https://user-images.githubusercontent.com/1948812/30620054-e384dc1e-9d57-11e7-8d6c-0b744d740f29.png)

**Comment by DonJayamanne** [comment]
Closed with #1224

**Comment by lmazuel** [comment]
@DonJayamanne  @brettcannon  Could you find as well env in ".tox/pyXX"?

**Comment by DonJayamanne** [comment]
Discussed with @huguesv
Add ability to query ```environments.txt``` file under ```%USERPROFILE%\.conda``` directory.
This seems to have more entries than those returned by ```conda info --envs```
