### ISSUE TITLE
Ability to create a virtual environment

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#1149]

**Comment by brettcannon** [comment]
And since I'm a "don't have a command in your editor that you can do from the terminal in a single command", it should probably automatically run` pip` or `conda` if you have a `requirements.txt` or `environment.yml` file, respectively (bonus points if you let people choose when `*requirements.txt` matches multiple files).

**Comment by brettcannon** [comment]
Thus this can tie into #1150

**Comment by DonJayamanne** [comment]
Closing in favor of #1150
