### ISSUE TITLE
Could you please add a python tree view?

### ISSUE THREAD

**Issue by wxkdesky** [DonJayamanne/pythonVSCode#1206]
It will be a great feature if tree view is added. For example, we can review all the code structure and just click some class to navigate there.

**Comment by DonJayamanne** [comment]
@wxkdesky 
Are you referring to a Code Outline for the currently active file?

**Comment by wxkdesky** [comment]
@DonJayamanne 
yes, similar with that~ It is a symbol tree in which I can see all the structure of my python code in currently active file(of course, if can find other connected symbols in other files will be a plus.), Just like many other python IDE provided, When I click a class name in the symbol tree, the tree will expand and show members of the class, e.g., functions, properties, etc.

**Comment by NaccOll** [comment]
@wxkdesky I think that you can use [Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline) to solve your problem. As follows:
[![https://gyazo.com/eb716c1e2b9bb5132f5549e7600c895e](https://i.gyazo.com/eb716c1e2b9bb5132f5549e7600c895e.png)](https://gyazo.com/eb716c1e2b9bb5132f5549e7600c895e)

@DonJayamanne I hope that the extension can offer the information of symbol about import in file rather than in workspace. Of course this is not a critical task. After all, by looking at the source code, the workspace symbols are generated by ctags, and the file symbols are generated by jedi. After trying,the `import` of the symbol information that is generated by jedi   will point to the source file, and can not be used normally.
