### ISSUE TITLE
RFE: Support Remote Interpreter

### ISSUE THREAD

**Issue by satyenr** [DonJayamanne/pythonVSCode#123]
The ability to run code on a remote machine is awesome. You can develop on a Windows PC or a Mac while running and debugging on a remote Linux server. PyCharm supports such a feature - https://www.jetbrains.com/help/pycharm/2016.1/configuring-remote-python-interpreters.html.

Having a remote interpreter also helps when the remote machine already has a functional Python environment - possibly managed by someone else - which you don't want to/can't replicate on your local machine.

**Comment by DonJayamanne** [comment]
This is a great suggestion. The architecture of VSCode and the extension supports this. However this would require a lot of effort, primarily in two parts. One would be to sync the two environments and the other would be the creation of a proxy component that sits on the server to manage all of the comms and surely enough this would have to be developed in python. 

However, this would require weeks if not longer to build. But something that I will most definitely explore as a side project.

**Comment by satyenr** [comment]
Thanks for accepting this RFE. I was trying to add this feature myself, but the lack of knowledge of VSCode related stuff and other priorities forcedme but that project aside for the time being.

**Comment by DonJayamanne** [comment]
Todo: Add support for docker containers as per #179

**Comment by DonJayamanne** [comment]
Suggestions for #183

**Comment by DonJayamanne** [comment]
@vbem, @satyenr , @satyenr, @nffdiogosilva
Hi everyone, I would like to re-visit this to understand the requirements and the constraints.

Here are some of the environments (usages):
- Docker/vagrant containers
- Remove servers (linux, mac, windows)

Requirements:
- Linting (code analysis)
- Code navigation (find references, go to definition, etc)
- Refactoring
- Debugging (done, this works today, but SSH is to be looked at - separate issue)

One possible solution I'm thinking of is:
- Install nodejs on the remote server
- Install a npm package (nodejs module)
- Start a socket server on this target server
- VS Code will communicate with the remote server over a socket connection

This is the easiest solution and quickest to implement.
However, this requires the installation of:
- nodejs on the server
- an npm package

Would this be acceptable?

The only other solution is the following one. However this would take a lot longer to develop and implment:
- install a python package on the server

**Comment by satyenr** [comment]
When I logged the ticket, I had the following use case in mind:

- Remote server has a fully configured Python environment, which is more or less identical to the deployment setup.
- The developer workstation may have Python installed, but it doesn't the fully configured environment. While it is possible to build a virtual environment containing the required modules in many cases, some modules don't work cross-platform, or are hard to compile. In any case, it is always preferable to development using an environment that is similar, if not identical, to the deployment environment.
- The development and deployment environments may even be running different operating systems.

As a result, linting, code-completion etc don't work as expected and end up causing more trouble than helping. A workaround is to run VSCode in a VNC session, or using X forwarding. In both cases, responsiveness of the UI is a function of network connectivity/load.

Originally, I had imagined that it will be implemented by running commands on the remote machine over SSH - that is what PyCharm does. Not sure if they maintain the connection as long as the IDE is open.

Using SSH ensures that you don't have to worry about things like authentication, managing a daemon on the remote machine etc. But using SSH means assuming that the client has a working SSH client - something you can't assume about Windows clients. I suspect PyCharm may be using its own SSH client - something I don't think is trivial to implement.

Your idea of using a socket server on remote machine seems like a good one. I don't mind which language it is implemented in. Python would be ideal, since we are anyway assuming that python is installed on the remote machine. But I am fine with NodeJS as well. As long as the protocol is open, someone can always implement a python version later.

> install a python package on the server
I assume you meant - install a python package on the remote which is then run as a daemon listening for requests from VSCode. Let me know if that is not the case.

**Comment by DonJayamanne** [comment]
@satyenr
>I assume you meant - install a python package on the remote which is then run as a daemon listening for requests from VSCode. Let me know if that is not the case.

Yes, you are right. Will try to start with the node daemon, and later move it to a python daemon.

**Comment by satyenr** [comment]
Sounds like a good plan to me. I can help with the Python part if you want. 

I don't have any experience with NodeJS, unfortunately.

**Comment by nffdiogosilvadc** [comment]
Hello =),

How is the current state of this issue?

Thank you

**Comment by DonJayamanne** [comment]
@nffdiogosilvadc 
no work has started on this, as there isn't much interest in this feature. Except possibly for the two of you.

**Comment by aventurella** [comment]
I'll raise my hand for this.  Our whole dev team formerly relied on vagarant and currently relies on docker to do all of our development.  Specifically during development, we use docker-compose to ensure all of the devs are running the same environment. 

Today we use Anaconda + Sublime. I have been exploring Visual Studio Code for Python development and something similar is a must. This looks to be where it will originate from so I can't thank you enough for even discussing it.

In our docker development case we just start up a new container that has the anaconda remote server on it. It gets the volumes from the django application, so it has access to all of the code currently running:

```
volumes:
  - ./django:/usr/app
  - /usr/local/lib/python3.5
```

We also deploy on docker, so if this were a: We need to debug a running server we would end up doing something similar, just attaching the container and disposing of it when done. From that point of view I have absolutely no issue with this workflow:

```
- Install nodejs on the remote server
- Install a npm package (nodejs module)
- Start a socket server on this target server
```

I am also aware that not everyone uses Docker. I only mention the Docker use case here for those that may also depend on it. Naturally every deployment would differ and have different needs.

**Comment by mgallagher** [comment]
+1 
this would be amazing

**Comment by nffdiogosilva** [comment]
Now that it seems that more people are interested in this feature, will it return to roadmap again?

**Comment by DonJayamanne** [comment]
Agreed, looks like there's enough interest here to get this into the roadmap now. 
There are two ways to go about this. I'll post both options, so as to get the feedback.

**Comment by DonJayamanne** [comment]
There are two ways to implement this feature: 
Option 1: Add dependency on node.js on the remote server

Benefit: Easier to develop
This is the easiest option for me (less python code), more node.js (javascript) code - i'm familiar with this

**Comment by DonJayamanne** [comment]
There are two ways to implement this feature: 
### Option 2: Add dependency on node.js on the remote server

Benefit: No dependency on node.js (except some other python libraries that I'll have to write)
Will require more work as I'll need to write everything from scratch using Python (this isn't my language of choice).

**Comment by DonJayamanne** [comment]
FYI, I'll commence the work with the node.js approach (Option 1).

**Comment by satyenr** [comment]
> Option 2: Add dependency on node.js on the remote server

You meant, "Add a Python module on the remote server", methinks.

**Comment by sierran** [comment]
For my team it is mandatory functionality without which we can not work, so fingers crossed :)

**Comment by ianfitzpatrick** [comment]
Hoping for this too. This is single feature is what's keeping me from switching to Visual Studio Code. Would be amazing if this lands!

**Comment by wasinski** [comment]
Another word of encouragement: this will be an absolute killer feature!

**Comment by peymanmortazavi** [comment]
👍 I'll switch to VSCode at work if this feature becomes available.

**Comment by gulshan** [comment]
https://github.com/palantir/python-language-server
Will this be any help?

**Comment by DonJayamanne** [comment]
Thanks, that just might work

**Comment by adlermedrado** [comment]
+1 to this feature. It'll be great.

**Comment by satyenr** [comment]
Seems like [Anaconda](http://damnwidget.github.io/anaconda/) (Sublime Text) has implemented this [feature](http://damnwidget.github.io/anaconda/remote_interpreter/) using a similar approach. A daemon (written in Python) listens on a given TCP port in the remote host. I have tried it - and my initial impression is that it works well enough.

@DonJayamanne If you haven't started working on this already, it may be worth looking at Anaconda to see if the server can be reused here. The code is available under GPLv3.

For what it is worth, PyCharm maintains an SSH connection with the remote host to achieve this.

**Comment by YAmikep** [comment]
👍 Hoping for this too. Would be amazing if this lands! Thanks

**Comment by liqing-ustc** [comment]
Hoping for this feature!!!

**Comment by tony-garcia** [comment]
+1

I'm using VSCode for most things these days but for a few projects the dev server is in a python Docker container so I'm still using PyCharm for those (since it allows associating a project to a python interpreter in a Docker container or docker-compose service). Would be cool to just use VSCode for everthing.

**Comment by johnnywell** [comment]
+1 
I recently heard about this extension on Talk Python to me and switched to VS Code since then. I'm really looking forward to seeing this in action!

**Comment by jaymickey** [comment]
+1. I develop mostly on a Windows machine, and had planned to utilise a Linux Docker container to develop a flask based web application, but was disappointed to see that there is currently no way to do this while still having access to code completion (intellisense), linting, etc.

**Comment by wsgeek12** [comment]
This would be great yes yes yes +1

**Comment by IBestuzhev** [comment]
+1. It would be a nice feature as I often use Docker (and sometimes Vagrant) to set-up the environment.

I can share what I use now.

For pylint it's quite easy, but does not work too fast unfortunately. I used a custom path for pylint and point it  to my custom [.pylint.py (gist)](https://gist.github.com/IBestuzhev/d022446f71267591be76fb48152175b7).

I was trying to do the same with jedi, but I did not manage to pass the stdin/stdout connection. I modified `python.jediPath` to point to jedi.py file from that [gist](https://gist.github.com/IBestuzhev/d022446f71267591be76fb48152175b7#file-jedi-py). Unfortunately due to some stdin/stdout issues I was able to do it only if I modify completion.py (the one in the docker) to process one request per time. I just added a `break` to `watch` method. Also there is something in docker that prevents from running it under `exec`, only `run` works. 

This jedi setup is working but it's really slow to use. Obviously it's a terrible idea to deploy the container every time, it was just proof of concept. I think replacing the communication to tcp will speed it up. 

So ideally is to have TCP communication between `client/providers/jediProxy` and `pythonFiles/completion`. In this case it will be easy to port-forward the connection to remote host.

Or as workaround it can be TCP communication between `jedi.py` from `python.jediPath` to modified `completion.py` that runs on remote. But this way is dirtier, as custom jedi.py file should block on import and prevent execution of some code from original completion.py.

Another thing that is needed here is path mapping. 

But I hope someone may find this ideas useful and can extend it.

**Comment by DonJayamanne** [comment]
@IBestuzhev wow, thanks, will try to get started on this. busy with a lot of things.
But this will surely make things easier.

**Comment by IBestuzhev** [comment]
@DonJayamanne Thanks!

My example is for docker, but I think it's not bound to docker that much. For TCP connection there is ssh port forwarding, so it should not really matter if it connects to some local listener, or listener under docker with `--port` option, or listener on remote server with `ssh -L` tunnel. 

For running pylint it can be ssh again, it support to execute command remotely instead of opening shell. The problem here is Windows developers, who will use not default implementation, but putty, `bash -c "ssh ..."` or cygwin. But it should not introduce problems, well, I started to use it with .bat file on Windows first.

It would be nice if plugin can detect Docker or Vagrant, as Anaconda does, but as for me it should be in future releases.

I checked the [Language Server implementation](https://github.com/palantir/python-language-server). It implements both communications. The language server can be started locally as process and use stdin/stdout. Or it can be connect to TCP, and server should be started manually to accept JSON RPC requests. But the implementation of TCP server is not "production ready", I'd say that project is in alpha state and it often fails with segfaults.

**Comment by gyermolenko** [comment]
I understand that this feature is huge and I apologize in advance for this question, but ..

Could someone please tell me some approximate date (or release number) when the feature could be ready?

**Comment by DonJayamanne** [comment]
No date yet, sorry. Only developer working on this, and number of issues/requests is growing.
Will try to get started on this soon.
Would appreciate some help/PRs.
Thanks

**Comment by gyermolenko** [comment]
@DonJayamanne thanks for reply

**Comment by dholth** [comment]
I managed to get a remote autocompletion server running like so. A script on the local machine runs python on the remote machine via ssh, and there is a copy of pythonFiles over there. Since the paths on the remote host are not the same, 'go to definition' produces 'File not found' errors, but since the remote filesystem is also mapped locally this could be solved by a mapping between remote and local paths. It is a bit slow but that could just be the virtual machine....

`#!/bin/sh
ssh -t vagrant@127.0.0.1 -p 2222 -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /path/to/.vagrant/machines/default/virtualbox/private_key "cd prog/pythonFiles; ~/opt/pyenv/bin/python" "$@"
`

**Comment by Ox24** [comment]
+1 for remote python interpreter to enable remote rpi dev.

**Comment by tonyskidmore** [comment]
I am only really just starting with Python and vscode but I am now developing in our remote Linux dev environment using a Windows laptop. This feature would be brilliant. Thanks for the vscode Python plugin by the way, it is awesome.

**Comment by Ghopper21** [comment]
This is one of the most important features that PyCharm has which prevents me from switching over to VSCode completely. The use case for me is on Windows 10 with the Ubuntu subsystem (a.k.a. Bash for Windows). I have my local dev environment in the Ubuntu subsystem so that it is as close as possible to the production server. I run an localhost SSH server in the Ubuntu subsystem and connect to it via PyCharm's remote Python interpreter feature, which as you note above uses SSH. Works great.

Not saying you should do this for VSCode via SSH -- just hoping that whatever you do it will work in this situation -- a single Windows 10 with the local dev environment in the Ubuntu subsystem on the same machine.

Thanks for the plugin and for giving us hope that this may come to pass! Exciting times for VSCode.

**Comment by DonJayamanne** [comment]
This will be looked into over the new few weeks/months.

**Comment by wklm** [comment]
+1 

@DonJayamanne could you consider a support for remote interpreters  running in docker containers? 
Pycharm provides it and I find it super useful

**Comment by Zverushko** [comment]
+1

**Comment by valentjedi** [comment]
While we all patiently (or not so patiently ;)) waiting for this feature to be implementing, I'll describe `sshfs` workaround I use now:
I have dev docker container with python and all site-packages installed and opened ssh on some port `PORT`.
So I've installed `sshfs` (little guide for ubuntu can be found [here](https://unix.stackexchange.com/a/202919/245683)), and then I've mounted my docker container's fs to my local host like this:

`sshfs -p PORT -o idmap=user docker_ssh_user@docker_host_or_ip:/ ~/.docker/mountpoint`

And now I'm able to select workspace interpreter from inside vscode or just paste its path to .vscode inside my project root. Something like this could work:

`"python.pythonPath": "~/.docker/mountpoint/usr/local/bin/python3.6"`

Hope it'll help somebody.

**Comment by patelkunal** [comment]
I would also love to use this feature in vscode. Because vscode's ntellisense is unbeatable with any-other code editors (sublime and atom). On top of that I use different vagrant environments for all project to keep everything clean and separate. And that way I need to configure settings to use interpreter from vagrant in .vscode folder and done.

+1 for this feature.

**Comment by cjfinnell** [comment]
+1

**Comment by FuriouslyCurious** [comment]
Upvoting this RFE: Dockerized Python is the best thing since the invention of bread.

**Comment by satyenr** [comment]
Hi @DonJayamanne,

Any chance of this gaining traction anytime soon? With the number of people interested, I'd think this warrants slightly more attention. Just trying to get an idea of where it stands in terms of priority. I know you are the only developer working on this, so no pressure! :-)

Thanks!

**Comment by Ghopper21** [comment]
@valentjedi thanks for this tip. I'm going to try the `sshfs` approach with Windows 10 + Bash on Windows. Will report back if it works.

**Comment by mghval** [comment]
@Ghopper21 Did it work on windows?

**Comment by akashparihar** [comment]
+1 for this.

**Comment by amarynets** [comment]
+1 for this. It will be amazing

**Comment by oppianmatt** [comment]
Would be good if the docker containing python is treated just like a local python. Pycharm have got it down good, so might be worth seeing how they did it.

You tell the project which python to use (and the python could be local or in a docker). If you say remote, it shows you a list of built containers and you pick the one that contains your python interpreter.  It sets up a run config for it.

Looking at it, they run the container, mount your code in it, and hook into the python that starts to do a remote debug session with the IDE.

Surely it doesn't matter above (option 1 or option 2) you go with as that will be hidden to us. We wouldn't need to change our containers. Once we pick the container, it would install the hooks it needs on startup of the container.

**Comment by sfdye** [comment]
+1
I will move from pycharm to vscode once this feature is available.

**Comment by egrgdam** [comment]
+1 for remote interpreter and big thanks to Don for python plugin!
Also those who managed to set up solution with sshfs on the WSL I'm very interested in guide how to do so... Fuse is making problems in WSL.

**Comment by FuriouslyCurious** [comment]
Hey @DonJayamanne I think I might have a potential solution for this RFE since it is the most requested RFE out here.

The Anaconda add-on for Sublime Text 3 provides remote interpreter support for linting and debugging through "minserver.py" file.  It is open-source and you might be able to rely on the same file for providing remoter Dockerized interpreter support for Python-VSCode.

**HOWTO process for connecting local IDE to remote Dockerized Python interpreter:**
https://github.com/DamnWidget/anaconda/wiki/Anaconda-v2:-Using-a-remote-python-interpreter-through-Docker#run-anacondas-minserver-in-its-own-container

**minserver.py code:**
https://github.com/DamnWidget/anaconda/blob/master/anaconda_server/minserver.py

_Shell wrapper around minserver:_ 
https://github.com/DamnWidget/anaconda/blob/master/anaconda_server/docker/start

**Comment by brettcannon** [comment]
@FuriouslyCurious unfortunately the code is GPL which means it would be tricky for the extension to use it.

**Comment by FuriouslyCurious** [comment]
@brettcannon Oh I see - can you elaborate?  I thought that forking GPL code was legal, so your clarification will help me out in future.

**Comment by brettcannon** [comment]
@FuriouslyCurious you can fork, but then you have to keep the license GPL. Now IANAL, but basically things get messy as basically anything that contains GPL code then has to act like as if it is also under GPL. So if the extension started to distribute GPL'ed code it would have to follow the GPL itself (instead of MIT like it is currently licensed).

**Comment by splendido** [comment]
I'm also really interested in this feature as our team is also using Docker containers as the preferred development environment.

FYI, [Docker Linter](https://marketplace.visualstudio.com/items?itemName=henriiik.docker-linter) is another package, not yet referenced within this thread, trying to partially address the same goal. It seems it simply run linting commands attaching to docker containers on the fly though... see [this line](https://github.com/henriiik/vscode-docker-linter/blob/e94c6937264a9f7af1d802740a7c3dc97e8f84a8/server/src/server.ts#L163) and [this line](https://github.com/henriiik/vscode-docker-linter/blob/e94c6937264a9f7af1d802740a7c3dc97e8f84a8/client/package.json#L164).

**Comment by hujianxin** [comment]
If there is this function, very good.
If there is not this function, also good! 😄 
Any way, pythonVSCode is a great extension

**Comment by bigkrp** [comment]
+1

**Comment by DonJayamanne** [comment]
Closing in favor of https://github.com/Microsoft/vscode-python/issues/79
