### ISSUE TITLE
Stopping Debugging skips finally clauses

### ISSUE THREAD

**Issue by iFreilicht** [DonJayamanne/pythonVSCode#1337]
## Environment data
VS Code version: 1.17.2
Python Extension version:  0.7.0
Python Version: 3.4.3
OS and version: Ubuntu LTS 14.04

## Actual behavior
When stopping debugging by clicking Stop in the debugging toolbar, finally clauses are not executed.

## Expected  behavior
Finally clauses should be executed as they are when the SystemExit or KeyboardInterrupt exception is raised.

I understand that the debugger needs to be able to kill a hanging process (or one that catches exit-exceptions), though, so this is likely by design. 
I guess the real issue is that I am unable to generate one of the above exceptions in a debug session.

## Steps to reproduce:  
-  [Download this gist](https://gist.github.com/iFreilicht/40adede4675f435facfe39ef77cfb614)
-  Run it with the python debugger in vscode
-  Wait for the "Sleeping..." strings to be printed to the Debug Console
-  Stop execution and check whether the line "Reached finally clause!" is printed

## Logs
Output from ```Debug Console``` output panel  
```
Sleeping...
Sleeping...
Sleeping...
Sleeping...
```

**Comment by DonJayamanne** [comment]
Unfortunately I don't see how this could be achieved, as the process is terminated (instead of sending keyboard interrupt signal or the like). 
Also, looking a Visual Studio (PTVS) and PyCharm, they both exhibit the exact same behavior. 

At this stage I'll be closing the issue due to the above two reasons.
If you believe this can be resolved with a code change, then please do feel free to submit a PR.

**Comment by iFreilicht** [comment]
Consistency is a good argument here. I'll try to look into it when I have time.
