### ISSUE TITLE
Do not use

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/pythonVSCode#183]
Please add your feature requests (suggestions) against this issue.
- Intellisense and Linting
  - Context actions for some linter messages
  - Disable autocompletion in comments
    (https://github.com/DonJayamanne/pythonVSCode/issues/30#issuecomment-240211811))
- Miscellaneous tools
  - Code coverage
  - Profiler
- Remote Interpreter
- Miscellaneous IDE enhancements
  - Autogenerate docstring
  - ~~Workspace Symbols~~
  - Folding docstrings (VS Code Issue [#9786](https://github.com/Microsoft/vscode/issues/9786) and VS Code PR [#9605](https://github.com/Microsoft/vscode/pull/9605))
- Debugging enhancements  
  - Securely debugging Python applications in the cloud (Azure, AWS or Google Cloud)

**Comment by CHEN-Zhihan** [comment]
Add syntax highlight for keyword “in”,"and","not","is","or"

**Comment by harangue** [comment]
Remote debugging over SSH would be huge! ++

**Comment by rogersachan** [comment]
#195

**Comment by iband** [comment]
Code completion also adding arguments, e.g. typing 
`sklearn.cross_validation.KFold(` shows all possible arguments:
`sklearn.cross_validation.KFold(n=0, n_folds=3, shuffle=False, random_state=None)`
Currently it doesn't show anything after you type "(".

**Comment by DonJayamanne** [comment]
@iband , the feature you have requested has been developed and will be in the next release #71

**Comment by iband** [comment]
When hovering methods with long description there's no way to see it completely. 
[Example for 'scale' method](http://iva-soft.com/ScreenShot.png)
Would be nice to find some solution for that. One way is to use `Ctrl + Space, Space` shortcut that shows description, but it's not marked up that nicely.
[Example](http://iva-soft.com/ScreenShot2.png)

**Comment by SeijiSuenaga** [comment]
Would be great to have code folding for classes, functions, etc.  (Issue #192 only mentions folding docstrings.)

**Comment by DonJayamanne** [comment]
@SeijiSuenaga Code folding feature for classes and functions is available today.

**Comment by SeijiSuenaga** [comment]
Oops, sorry, I didn't realize the +/- boxes were hidden unless hovering over the left side. Anyway, thanks for the great extension. :+1:

**Comment by DonJayamanne** [comment]
No need to be sorry, if you hadn't raised this issue you provably would have never found it

**Comment by vstoykov** [comment]
@LRPalacios Django templates syntax probably does not belong here. I think that separate extension must be made for Django syntax template syntax.

**Comment by iband** [comment]
Thank you for Intellisense for parameters, though it's not working if you want to name the parameter, e.g. typing `np.linspace(start=1, stop=10, num=200)` instead of `np.linspace(1, 10, 200)`. 
It the first case it shows only the first parameter:
<img width="780" alt="screen shot 2016-07-18 at 2 07 51 pm" src="https://cloud.githubusercontent.com/assets/333948/16910257/83c639f8-4cf9-11e6-8dde-76f0a0821031.png">

**Comment by DonJayamanne** [comment]
@iband Let's limit this issue just for feature requests, else we will end up with anything and everything in here . I will create a separate issue for what you have raised.

**Comment by rooshipatel** [comment]
First, I would like to say that the Python extension on VS Code is amazing. I would like to see a little more syntax highlighting, in the same manner that Atom and Sublime Text highlight Python code. For instance, keywords like raw_input, open, dict, etc. This is a very helpful feature for beginner programmers like myself. Keep up the great work and let me know if adding more syntax highlighting is already a feature.

**Comment by samba2** [comment]
automated imports would be great. So I start using a symbol and the IDE suggests to import the missing class/ function. This safes me having to know the package paths of the modules

**Comment by vstoykov** [comment]
I think that the automated imports are bad thing. You should know what are you importing and where it is located.

**Comment by samba2** [comment]
I am currently using Pycharm a lot. Pressing ALT+Enter on an unresolved symbol gives me a list of the possible modules to import. I quickly select the right on and press Enter again. This takes me maximum 2 seconds without a) breaking my coding workflow by jumping to the import section on top of the module b) saves me wasting time with manual typing c) saves me from memorizing all the package path I need.

For me these let's call it "guided imports" are a must have for working on bigger projects.

**Comment by DonJayamanne** [comment]
@samba2, I like the idea of presenting the user with the options to import from rather than trying to guess it. Hopefully someone can also help with some of these changes 😄

**Comment by sth4nth** [comment]
+++++ for Integrating IPython
Currently python becomes the most widely used scientific computing language. The AI fever enhanced this trend. A lot of people use the python toolchain (numpy, scipy, matplotlib, ipython) to do numeric computing stuff, such as Deep learning. ipython integration is a big plus for those people.

**Comment by bufke** [comment]
Type hinting support. See https://docs.python.org/3/library/typing.html

PyCharm is a good example of built in support.

**Comment by DonJayamanne** [comment]
@bufke, There's a known issue with regards to supporting this (it is meant to work, but doesn't work in Python 3.5) [here's the issue](https://github.com/DonJayamanne/pythonVSCode/issues/201)

**Comment by alirezaafzalaghaei** [comment]
hey,
please add cython support(cdef,...)

**Comment by rogersachan** [comment]
@DonJayamanne Bash on Windows is out now, so there is now somewhat solid reason to support it.

**Comment by Avrong** [comment]
Add Jinja2 (Flask) and Django template support

**Comment by vbem** [comment]
**Remote Interpreter** + **Remote debugging over SSH** are extremely useful for **back-end** python development.

**Comment by ysfjwd** [comment]
imho, auto docstrings is a must. can we reuse the from sublime that does this?

**Comment by Thraka** [comment]
Cool to have https://github.com/pythonnet/pythonnet support. 

Then I can get intellisense on .NET libraries used by Python.

**Comment by DonJayamanne** [comment]
Consider using [mypy](https://github.com/python/mypy) for autocompete (with support for pep8) from #282

**Comment by gandhis1** [comment]
I've searched this GitHub but didn't find much existing progress on IPython integration. Only comments I want to make is that RStudio-like behavior, where one can execute highlighted code snippets in a long-running IPython instance, is vital. This needs to be accessible through a keyboard shortcut (not a manual copy + paste as it is now). Right now it only appears one has the ability to run the entire script through a shortcut.

Thanks for listening, I'm probably far from the only one who depends on this functionality.

**Comment by DonJayamanne** [comment]
@gandhis1 , my plan is to look at IPython next. I have already started researching in this space. Any contributions specially in this space is most welcome.

**Comment by thekorn** [comment]
First of all, thanks @DonJayamanne for this brilliant extension.
The only feature request I have is very basic: allow arbitrary linter and test commands.
Here are a few use cases:

* I'm developing a django application, with using the `django-nose` testrunner my tests are executed like `python manage.py test` 
* I'm developing my django app in a dockerized environment, `pylint` can be executed as `docker-compose run --rm web pylint --load-plugins pylint_django ...`

I'm proposal is something like adding a new set of settings like `python.unitTest.customCommand=<array>` and `python.unittest.customFlavor=(nose|pytest|...)` and something similar for a custom linter setting. It's then up to the user of the extension to provide the command, and to make sure that the results are correctly formated (like defined by flavor)

As of now I have a workaround for this at least for the linter, which is working but ugly, and needs some changes to the input file path:


```
settings.json:

{
    "python.linting.pylintPath": "docker-compose",
    "python.linting.pylintArgs": [
        "run",
        "--rm",
        "web",
        "pylint",
        "--load-plugins pylint_django"
    ]
...
}

docker entrypoint (convert absolute location on the host, to absolut location in the container):
[...]
if [[ $RUN_CMD == *"pylint"* ]]; then
	if [ -z ${HOST_WORKDIR+x} ]; then
		echo "HOST_WORKDIR is unset, not changing the path"
	elif [[ ! ${HOST_WORKDIR} ]]; then
		echo "HOST_WORKDIR is empty, not changing the path"
  else
		args=( "$@" )
		for ((i=0; i < ${#args[@]}; i++))
		do
			if [[ ${args[$i]} == "${HOST_WORKDIR}"* ]]; then
				args[$i]="${DOCKER_WORKDIR}${args[$i]#$HOST_WORKDIR}"
			fi
		done
		RUN_CMD="${args[@]}"
	fi
fi
```

something similar does not work for unittests, because of (https://github.com/DonJayamanne/pythonVSCode/issues/301)

**Comment by csprabala** [comment]
Code hierarchy / code structure of the files that are currently being edited. This would be immensely helpful while working on large code files.

**Comment by keathmilligan** [comment]
I'd like to see lint-as-you-type behavior consistent with eslint, tslint and other linter extensions (no need to turn on auto-save).

**Comment by ferdynice** [comment]
Great extension.

Global symbol search would be really great to have. You can probably use ctags or jedi for this, building an in-memory map of symbols.

**Comment by DonJayamanne** [comment]
@LRPalacios , @Avrong , @nnfdiogosilva, @bufke , @mmclark, @wengole, @abdelouahabb, @davehamby, @IornL, @ysfjwd , @deronnax, @LRPalacios , @goowell
Debugging django templates has been added in the latest released (however there is still no support for syntax highlighthing nor intellisense in django templates)

**Comment by abdelouahabb** [comment]
@DonJayamanne for syntaxe highlighting, it will be easy to add it, since TextMate have already Django support, 
i have already done this on Tornado 
https://github.com/abdelouahabb/vscode-tornado

**Comment by gzamboni** [comment]
In Django projects will be awesome to have Intellisense  for ForeignKeys and related objects in Django model classes.

**Comment by martinfiers** [comment]
I'm not sure if this would be a new feature or something I missed. Is it possible to update the PYTHONPATH somehow? Right now, when working on a project, I first need to update the PYTHONPATH on the console before launching the command-line 'code'. Could it be part of the project settings?

**Comment by vstoykov** [comment]
@martinfiers if you set in your Settings the path to the Python interpreter
```
"python.pythonPath": "/path/to/your/bin/python"
```
then everything will work correctly. You can do that per project in  "Preferenses -> Workspace Settings"

**Comment by martinfiers** [comment]
Dear @vstoykov : thanks very much for your answer. Although that's not exactly what I was looking for. What I wanted to ask is whether we can modify the PYTHONPATH environmental variable, which is different from the path to the python interpreter. See the documentation here: https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH. It is the list of folders that the interpreter searches through in order to find additional modules. 

Thanks!
Martin

**Comment by vstoykov** [comment]
@martinfiers I thought that something in the builtin python features in VS Code was not working because when you start `code` it does not know which which virtual environment you are using for current project or something like that and for that reason does not know where to search for python modules (for autocomplete, or "Go to definition" for example).

Probably I misunderstood your question. Can you explain what exactly does not work and need modified PYTHONPATH in order to work?

**Comment by jongmmm** [comment]
Hello all: I wonder if I can change text colors of ipython `Results` window. I use white background and some colors are not really legible with error message. Thanks, JM

**Comment by martinfiers** [comment]
@vstoykov : changing the PYTHONPATH would be useful if you're developing your own Python packages and modules. Suppose we have a large project located at /home/user/projectA which is not known to the Python installation. In that case, we want to update PYTHONPATH and add /home/user/projectA to it, after which the Python interpreter will pick up the new module.

One way to do it would be to set the PYTHONPATH in the terminal and then start code:

`export PYTHONPATH=$PYTHONPATH:/home/user/projectA`
`code /home/user/projectB_that_uses_projectA`

But it would be nice if you could set it from the editor, so that you don't have to repeat this step each time you open code and load a project.

Does that make sense?

**Comment by vstoykov** [comment]
@martinfiers for your case I think that in your case there is a solution that will not only work for visual studio  code but for everything.

You probably use virtual environments per project. Then just install install your `projectA` in devlop mode in the virtual environment of `projectB_that_uses_projectA`

Because `projectA` is reusable then it probbaly has `setup.py` file. The when you are in the virtual environment of projectB you need to go to projectA folder and execute:

    pip install -e .

or

    python setup.py develop

This will put a link in the virtual environment and any modifications in projectA will be reflected when running projectB without reinstalling the package.

**Comment by karlacio** [comment]
When working on a ipython/juniper with cells is easy to miss (visually) some cell delimiters `#%%`.

It would be better to have a more evident "graphical" separation from cell to cell to see at a glance where each cell start.

**Comment by DonJayamanne** [comment]
Closing this issue, please create separate items for features, suggestions and similar.

**Comment by martinfiers** [comment]
@vstoykov just wanted to thank for your answer. I think that will do. Also I assume you can set environmental varilables in your launch.json, so that can help as an alternative.

**Comment by talkaminker** [comment]
I want to be able to send cells for execution and debug(less important) on an external ipython kernel (for example one that I opened with qtconsole)

Normally when opening ipython you can connect to some other already open ipython kernel using:
`jupyter <app> --existing <path-to-connection-json-file>`
and you can get the connection json running 
`%connect_info` in any open ipython kernel

This is the only issue preventing me from switching from spyder (I need to run Qt (using `%pylab`) which I understand is not supported in vsc)
I just want to send cells and let them be executed in the qtconsole.
otherwise, amazing product. huge thanks!

**Comment by dogpower** [comment]
Expose command palette actions as actions that can be mapped to keyboard shortcuts, ie setting CMD-R to "Run Code in Terminal" would be really helpful!

**Comment by DonJayamanne** [comment]
You can configure shortcuts today for any and all commands, see here https://code.visualstudio.com/docs/customization/keybindings#_customizing-shortcuts

**Comment by dogpower** [comment]
@DonJayamanne Yes, that's the functionality I'm using - however I can't seem to find the exposed commands pertaining to the Python extension. I was expecting something along the lines of "python.run_code_in_terminal" or similar, however no Python related commands are available as far I can see.
Attached is a screenshot showing the issue: 
![image](https://cloud.githubusercontent.com/assets/11429187/23154537/a20ef664-f80e-11e6-8529-b9fe8b015497.png)

**Comment by DonJayamanne** [comment]
1. Open the Extensions panel   
2. Select the extension 'Python'  
3. Go into the 'Contributions' panel

see below, and you'll find a list of all the commands

<img width="1157" alt="screen shot 2017-02-21 at 7 04 09 pm" src="https://cloud.githubusercontent.com/assets/1948812/23155890/a75be906-f868-11e6-9c87-5d815735d736.png">

**Comment by eMerzh** [comment]
While coding, i've activated the formatOnSave option of vsCode.
it seems that there is no way to also sort import on save.

it would be really great if the format on save could do both :)

**Comment by kbakk** [comment]
_Note that I'm a beginner in Python._

When you create a new launch.json for a Python project (go into debug and click *Configure or fix 'launch.json'*), this is populated with the following configurations: Python, PySpark, Python Module, Integrated Terminal/Console, External Terminal/Console, Django, Flask, Flask (old), Pyramid, Watson, Attach (Remote Debug). 

As a user I may use only one or two of these, based on the project type. 

I suggest to only provide the most commonly used items (Python and Integrated Terminal/Console maybe), and allow the user to add more configurations as required using the *Add configuration* button in VS Code. 

This keeps the debug dropdown and *Ctrl+P > Select and Start Debugging* cleaner, as well as keeps the launch.json relevant to the project (not doing so may confuse the user of which debugger to use, when the user is not up to date on the project).

**Comment by Adrianacmy** [comment]
Is it possible to add a doc string snippet for functions, like below, or other good format, as long as it will show all params for different functions.
```def encrypt(text, key):
    '''
    :param text: 
    :param rot: 
    :return: 
    '''
```
Don't know how to code each param of different functions in python.json

**Comment by zgoda** [comment]
Select interpreter from list of virtualenvs and set search paths accordingly if `workon` command exists.

`workon` is shell command installed by [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/stable/). When invoked without argument it lists available virtualenvs under its control, in alphabetical order:

```
$ workon
bde
brewlog
cocos
...
tsp
twt
wsm
yg01
```

**Comment by tuhinkarmakar** [comment]
@DonJayamanne Will it be possible to add the following behaviour?

# Current Behaviour

- No documentation after a method has been selected (one has to hover over the method to view the doc)

![current](https://cloud.githubusercontent.com/assets/11135104/26521683/224c000e-430c-11e7-80c3-53053b44bc39.gif)

# Expected Behaviour

- More details about the parameters
- Documentation is shown even after a method has been selected and while the parameters are being typed
- Detailed documentation is shown. For example, the documentation for `sort()` should be pulled from [here](https://docs.python.org/3/library/stdtypes.html#list.sort)

![expected](https://cloud.githubusercontent.com/assets/11135104/26521742/95eaeb64-430d-11e7-83d8-954ca5d9eac7.gif)

**Comment by BlacKCaT27** [comment]
Suggestion for new feature:

Auto-generate property methods based on existing class member. 

example:

    class MyClass:
        def __init__(self):
            self.my_var = 1

via some mechanism (keyboard shortcut, right-click on my_var, etc), generate the following boilerplate from a template:

    class MyClass:
        def __init__(self):
            self.my_var = 1

        @property
        def my_var(self):
            return self._my_var

        @my_var.setter
        def my_var(self, value):
            self._my_var = value

Would be a wonderful feature to help developers refactoring 'old style' code to support properties. 

The only potential issue is that this boilerplate would, by default, cause this linter warning due to undefined behavior in how linters handle properties (or maybe it's just a bug in pylint): https://github.com/PyCQA/pylint/issues/409

There are two workarounds that could be added to the boilerplate to stop the linter warning (either declare self._my_var = None prior to calling the setter, or just set the pylint disable comment in the setter itself), or you could just ignore it and let users handle it themselves.

**Comment by rajasimon** [comment]
Please enable the option to run **SimpleHTTPServer** or **http.server**.

In my case after build the sphinx documentation I wanted to open the build html files in url. And thus needs to run the python server. If this feature integrated into pythonVSCode all I to do is run the build and start the documentation server. Cool right ?

**Comment by netheril96** [comment]
Suggestion: A command for restarting Jedi and other long running background processes this extension launches.

Today when some of them crashes, I have to restart the whole VSCode to get them working again.

**Comment by DonJayamanne** [comment]
Guys please try to create separate issue with your suggestions. Thanks

**Comment by nlmalc** [comment]
Could you please use the shebang at the start of the Python script to determine which Python executable to use?  My scripts say "#!/usr/bin/env python" or "#!/usr/bin/env python3", which is fairly convention.  It's quite annoying having debugging (and linting) failing because it's a Python2 script, but the debugger uses Python3.  

I'm on a Mac with the default Python (2) installed as well as Python3 via Homebrew, but this page is quite interesting with regards to the shebangs and how the Python3 launcher interprets them on Windows:
http://testerstories.com/2014/06/multiple-versions-of-python-on-windows/

**Comment by nlmalc** [comment]
Maybe this is a documentation issue (and my lack of understanding), or maybe it's an actual feature request: how do I work with multiple Python scripts in different folders?  Can launch.json be configured for different scripts with regards to the command line parameters to invoke them with, and (excepting my previous feature request) can it also be configured to use different versions of Python with different scripts?

**Comment by vors** [comment]
Hello!

Feature request: goto definition (Cmd+Click) in the mypy annotation (python 2)

**Comment by JGH1000** [comment]
Autoimport like in PyCharm, already mentioned in https://github.com/DonJayamanne/pythonVSCode/issues/764 and https://github.com/DonJayamanne/pythonVSCode/issues/513

**Comment by yofreke** [comment]
I would like to formally second <https://github.com/DonJayamanne/pythonVSCode/issues/183#issuecomment-251683272>.

The [current wiki](https://github.com/DonJayamanne/pythonVSCode/wiki/Linting#lint-as-you-type) could note that this is a poor solution, and that **real** as-you-type support is on the feature roadmap.

**Comment by adammhaile** [comment]
vscode does not seem to respect python virtual environments at all. This may actually be just a vscode issue and not necessarily with this extension though as even the build-in terminal doesn't respect the environment. To explain, this is my process with Atom:

```
~> workon bibliopixel
(bibliopixel) ~/dev/bibliopixel> atom .
```

Now, because I was in that virtualenv when I ran the atom command, it starts up in the context of that environment. It uses the correct python version and has access to all the packages installed in that environment.

As far as I can tell with vscode and the pythonVSCode extension, however, the only way I can do this is to set `python.pythonPath` either globally or in the `.vscode` config in the project directory root. Both of these are non-starters for me. For the global option, I often have one IDE open with one venv and another open in a different venv. And for the `.vscode` config option, it's just silly to have to clutter up my project directory even more.

Any way to get this to just simply respect the bash environment from which I started it? It has everything it needs to know :)

**Comment by vstoykov** [comment]
@adammhaile actually the current behavior is a good thing.

1. You have configuration which python to use by default if nothing is specified for the current workspace (For example you may want Python3 instead of the default Python2 in your distribution)
2. VSCode will automatically switch between python interpreters when you switch between workspaces (without closing VSCode)
3. In the past there was some problems with VSCode (or probably this extension) when it was started from command line with activated environment. It acted strange because it tried to use the interpreter from the environment but then it acted very strange (I forgot what exactly was the problems, but from this time I stopped to start VSCode from activated environment).
4. It's really easy to set (and forget) the interpreter for given workspace (project). Just hit  Ctrl+P, then type "select w" and you will see "Python: Select Workspace Interpreter", then hit Enter. You will see a list of all your Python interpreters (System python and those in `~/.virtualenvs`). Just select yours and from now on every time you open this workspace (no matter how) VSCode will know which interpreter to use.
5. Because of workspace symbols you will still have a file `.vscode/tags` in your workspace, which you need to ignore. Instead you can simply ignore the `.vscode/` directory, and VSCode will not bother you.

**Comment by jkyeung** [comment]
Is there a way to have automatic brace completion active but disable the automatic extra newline when pressing Enter? For example, if I have this (with the cursor shown as `|`):

    foo = (|)

And I press Enter, I get this:

    foo = (
        |
    )

Is there some setting so that I have this instead:

    foo = (
        |)

I apologize if this should be a VS Code issue, rather than an issue with this extension. (But I kind of dread posting an issue there, because its tracker is swamped.) But of course best of all would be if this already exists and someone can just point me to it. :)

**Comment by BenjaVR** [comment]
Not sure if this is possible, but automatically enabling the virtual environment you use for a project if you open an integrated terminal would be really nice. Just like PyCharm does.

**Comment by DonJayamanne** [comment]
Closing this issue as it contains too many feature requests. Please create separate items for each request.

**Comment by liuhong12th** [comment]
Please don't make "stopOnEntry=true" default.
When I run a single-file project, I'd like to keep the folder clean.
I don't want to stop on entry, and don't want to create a ".vscode/launcher.json" file neither.
Or can you just add this config in the user's config file?

**Comment by thecylax** [comment]
Support for sphinx docstring format
Render docstrings compatible with sphinx syntaxe
