### ISSUE TITLE
using with Bash on Ubuntu for Windows

### ISSUE THREAD

**Issue by rogersachan** [DonJayamanne/pythonVSCode#195]
As August 2nd (the Windows 10 Anniversary Update) nears, I'd like to know if the Python VScode extension is compatible with the subsystem.

The Subsystem however is nothing more than a `bash.exe` as far as I know, so there may not be a path we can give a reference to.

**Comment by rogersachan** [comment]
Suggestions for #183

**Comment by DonJayamanne** [comment]
@rogersachan, I have absolutely no idea where to start from for this. From what I understand anything Bash on windows can only be accessed from within that environment (via the terminal) and not outside of it. Any help (PRs) on this would be appreciated

**Comment by Resousse** [comment]
Hi @rogersachan ,

I'm not sure to understand what you mean?
What would be the link between the python extension and bash?
Did you mean bash inside VSCode to replace the existing terminal?
Thanks

**Comment by Schandlich** [comment]
@Resousse I am going to guess that his situation is similar to mine.

1. I have Win 10 Anniversary and I have the Ubuntu subsystem turned on. 
2. I would like to just install python there vs an MSI/EXE/Whatever.
3. I can already use bash in VSCode by adding this to my settings.json file: `"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",`
4. Right now, since I am just writing a simple script, I have to go the integrated terminal window (or bash), and type in `python <filename>`
5. I would love to be able to debug in this scenario.

Again, just a guess.
