### ISSUE TITLE
Not support subprocess debug

### ISSUE THREAD

**Issue by Anniywell** [DonJayamanne/pythonVSCode#231]
I startup a subprocess in my python code, but I can't debug subprocess code.
My code:
`subprocess.call([sys.executable, os.path.join(dir, 'main.py')])`

**Comment by DonJayamanne** [comment]
Unfortunately you won't be able to debug this. 
You'd have to try and attach to that process. You can only debug one process at a time, not more.
The problem here is that you have launched a separate process and haven't let the debugger perform the launching, hence the debugger has absolutely no idea that a process was launched and it needs to be debugged. I don't believe other debuggers would support this either.

**Comment by Anniywell** [comment]
@DonJayamanne PyCharm and ipdb can debug it.

**Comment by DonJayamanne** [comment]
@Anniywell, Thats interesting, Either way, this extension doesn't support it. As mentioned you might want to consider trying to attach the debugger.

**Comment by Anniywell** [comment]
@DonJayamanne Thanks
