### ISSUE TITLE
mypy support

### ISSUE THREAD

**Issue by s-trooper** [DonJayamanne/pythonVSCode#282]
Hi, is a [mypy](https://github.com/python/mypy) support for linting and with [typeshed](https://github.com/python/typeshed) connected for better autocomplete in planing?

**Comment by DonJayamanne** [comment]
@s-trooper , never heard of it untill now. 
There are two suggestions here:  

- Autocomplete  
At the moment [Jedi](https://github.com/davidhalter/jedi) is used for autocomplete, and trying to implement another that would work along with or instead of Jedi would be a major task and would require some time for review and analysis.

Also, the Jedi library is meant to support [pep484](http://jedi.jedidjah.ch/en/latest/docs/features.html#general-features) in the current version , [however it doesn't due to a bug, which has been resolved in the dev branch](https://github.com/davidhalter/jedi/issues/742)

- Linting  
Having another linter does sound like a good option.
However that being said, the following statement on their website does make me wonder whether we should wait until a proper build is released:
[```Mypy is still experimental. There will be changes that break backward compatibility.```](http://mypy.readthedocs.io/en/latest/introduction.html)

**Comment by DonJayamanne** [comment]
@s-trooper , i have added the use of mypy as a linter into the feature requests #183.

**Comment by s-trooper** [comment]
thank you for time your have taken, my bad i don't recognize you use jedi as back-end. both linting and autocomplete with mypy are addressed by jedi, i don't have known that but pointed by you hint i see few ppl. from mypy in jedi project.

**Comment by DonJayamanne** [comment]
@s-trooper , thanks for mentioning that, as that project is maintained by the python organization. And that's a big deal. Where as Jedi seems to be maintained by a single person.

**Comment by DonJayamanne** [comment]
https://github.com/DonJayamanne/pythonVSCode/commit/d57233579b4f1b49760d13b025887ee782c104fb
