### ISSUE TITLE
can not debug

### ISSUE THREAD

**Issue by asdncg** [DonJayamanne/pythonVSCode#3]
debugger can not work.
debug console displayed "Pdb Closed false".

**Comment by DonJayamanne** [comment]
Hi, please could you test the latest version?. If it still doesn't work. Please could you send me a sample block of the code that falls over while debugging?

**Comment by MexieAndCo** [comment]
I'm having the same problem (Windows 8.1 (64-bit processor)). I get the same message in the debug console, and the python code never runs (progess indicator after launch just keeps going back and forth and a breakpoint near the beginning of the code is never hit).

**Comment by DonJayamanne** [comment]
Hi, I am using a 64 bit Windows 8 pc too. I haven't been able to replicate it. Please could you send me the sample code you have used. Also Please  could you confirm you have modified lauch.json to point to the right file

**Comment by Botong** [comment]
I dont have this issue, it works fine for me

**Comment by MexieAndCo** [comment]
Thanks for responding. I'm no longer having the it-doesn't-work problem. I do think I'm having a couple of minor problems. E.g., I was continuing execution of the program and it kept breaking on a line for which I hadn't set a breakpoint, and it seemed impossible to effectively remove this phantom breakpoint. I started to use VS Code recently, so I'm assuming that the problems I experience are probably due to my own inexperience; I've also a relative newbie with Python.
The program I was playing with is downloadXkcd.py from Automate the Boring Stuff with Python, by Al Sweigart on No Starch Press. It imports 'requests' and 'bs4' (Beautiful Soup) and it looks like some problems are related to the requests module. downloadXkcd.py is reasonably interesting and uses a bunch of modules, so it's good for learning (for me at least) and testing.
Thanks for authoring the plugin.
Larry Seltzer
 

    On Tuesday, January 26, 2016 1:37 PM, Botong <notifications@github.com> wrote:
 

 I dont have this issue, it works fine for me—

**Comment by asdncg** [comment]
I have solved this problem. 
In lanuch.json file, I set the value for "program"  from "__int__.py" to "${file}", then debuger worked well.

**Comment by DonJayamanne** [comment]
That's good news, I might consider changing the default value accordingly.

**Comment by moigagoo** [comment]
Hi!

I'm having the same issue. As far as I can see, it happens every time I try to Continue (F5).

I'm debugging a CherryPy-based web app. Since there's a server running, there's an infinite loop. Maybe pdb has issues with it. Nonetheless, if I'm debugging step by step with F10 and F11, the whole process runs just fine, up to the point when the server blocks. The debugger does _not _show "Pdb Closed False" error in this case, but the debugging effectively stops, since it doesn't go to any code invoked in the loop.

**Comment by DonJayamanne** [comment]
Yes, that's correct. The issue is with PDB. But i'm working on a fix for this. In a future release (next week), debugging of web applications (multi-threaded) apps will be possible (e.g. web apps, hopefully even remote debugging, and the like).
Hopefully the next debugger will be a proper debugger with plenty of capabilities.

**Comment by moigagoo** [comment]
That's amazing! Thanks for the fantastic work you're doing!

**Comment by talha252** [comment]
I don't if this will be covered in next release but I having a weird problem. I changed "program" entry to "${file}" in launch.json file. After that, I had to remove "stopOnEntry" because simply it caused error. The debugger gives an error if I make syntax error but it doesn't print any output when things are okay. I tried reinstall extension, played around with some settings however I couldn't just get it right. I don't know if this a issue or just my fault. Any suggestion are welcomed.

**Comment by DonJayamanne** [comment]
Printing out console out put was flakey with pdb, simply because pdb uses the console output as well. The new release will have better support for console output. I hope to release this sometime later today. How ever that is still not complete, bit much better than the pdb debugger in a number of ways.
