### ISSUE TITLE
`python.unitTest.nosetestPath` settings has no effect

### ISSUE THREAD

**Issue by thekorn** [DonJayamanne/pythonVSCode#301]
The `python.unitTest.nosetestPath` setting is documented as a way to define a custom path to the `nosetests` executable, however, even if this settings is changed in any configuration file, still the global `nosetests` executable is tried to use.

**Comment by DonJayamanne** [comment]
@thekorn, sorry, that needs to be  removed. Please configure the python.pythonPath in your workspace settings (settings.json). 
The reason is simple, one cannot have different versions of unittest  apart from what comes pre-installed with the interpreter. 
The plan is to remove the other paths too for other tests.

**Comment by DonJayamanne** [comment]
Reopening due to a usecase mentioned in #183.

**Comment by DonJayamanne** [comment]
@thekorn , sorry, I didn't read this properly. I thought you were referring to unitTestPath..
Will fix this asap, the new release will be available in a day, at most two.
