### ISSUE TITLE
Pylint - 'Unable to import module'

### ISSUE THREAD

**Issue by vidoardes** [DonJayamanne/pythonVSCode#394]
I am having trouble getting pylint to recognise relative module imports. I have empty __init__.py in my module folders, the imports work if I run the the file and the intellisense auto completes the module but pylint always says unable to import. Can anyone help?
[Example Project.zip](https://github.com/DonJayamanne/pythonVSCode/files/536162/Example.Project.zip)

**Comment by DonJayamanne** [comment]
Please  check the following links:
https://github.com/DonJayamanne/pythonVSCode/wiki/Troubleshooting-Linting
https://github.com/DonJayamanne/pythonVSCode/wiki/Python-Path-and-Version

**Comment by DonJayamanne** [comment]
@vidoardes , did you manage to get this working?

**Comment by vidoardes** [comment]
I didn't, but it occurs when running pylint from the command line so it has nothing to do with your vs code plugin. I'll close this off, thanks for your great work!

**Comment by davidghiurco** [comment]
I am having issues with relative imports on this as well. I am 100% sure that pylint is installed with the correct python version (running inside a virtual environment on my company's build server, and the virtual environment is provisioned every time the test job runs)

how can I specify the PYTHONPATH (either externally though an export command in bash, or internally with a sys.path.append, or from within the pylint CLI itself) so that when I give Pylint the positional argument which contains the python package which has all the python files that I want to test, it will resolve the relative imports within that package????

**Comment by erichiller** [comment]
I am having issues with this as well. I can import perfectly fine on the command line, and autocomplete even works for the modules which are supposedly missing.

I've tried explicitly setting the paths for pylint and python itself and it had no effect.

Not sure where the error could be from here.

I have Jupyter installed on the same machine and it functions fine. (not running jupyter through vscode though)

**Comment by erichiller** [comment]
This might help some more.

I checked the importers, using the example of the `json` module being imported, which pylint says it can not find.

```python
>>> sys.meta_path
[<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>]
```


Misses with:
```
importlib.machinery.FrozenImporter().find_spec('json')
importlib.machinery.BuiltinImporter().find_spec('json')
```

A hit with PathFinder
```
importlib.machinery.PathFinder().find_spec('json')
ModuleSpec(name='json', loader=<_frozen_importlib_external.SourcelessFileLoader object at 0x000001DB6BEF0128>, origin='C:\\Users\\ehiller\\AppData\\Local\\omega\\system\\python\\lib\\json\\__init__.pyc', submodule_search_locations=['C:\\Users\\ehiller\\AppData\\Local\\omega\\system\\python\\lib\\json'])
```

**Comment by erichiller** [comment]
Last item, sorry for the numerous updates, but I didn't want to (a) leave this as a dangling end for the author and thought (b) maybe this would help someone.

So, I fixed my looking issue, which also fixed my inline doc issue. Turns out I was running all `.pyc` / non-source versions of the core modules, like `json` which `pylint` will apparently not recognize even though they work perfectly fine. All of my pip-installed imports were source so pylint didn't have any issues there. I was let on to the cause when I noticed that items like json.* didn't have any documentation inline while TensorFlow or pandas did, which seemed odd at best.

Any ways. The fix.
Install Python properly.  (_or just copy over the source `/Lib`_)

**Comment by jcrben** [comment]
For those using pyenv and pyenv-virtualenv, `pyenv which python` seems to give the complete path when inside of a virtualenv.

**Comment by Kogam22** [comment]
@jcrben 
Can You Please Elaborate What You Mean By

> Any ways. The fix.
> Install Python properly. (or just copy over the source /Lib)

**Comment by DonJayamanne** [comment]
Please report issues on the Microsoft repo, I'll check it out there

**Comment by gopaltirupur** [comment]
https://code.visualstudio.com/docs/python/linting#_troubleshooting-linting
helped me.. 

"python.linting.pylintArgs": ["--load-plugins", "pylint_django"] was the issue

**Comment by gopaltirupur** [comment]
setting below solved for me

 "python.linting.pylintArgs": [           
            "--load-plugins", 
            "pylint_django"
        ]

**Comment by papakai** [comment]
I had also pylint showing this error up in vs code. Here my response on stack overflow that helped me getting this fixed: https://stackoverflow.com/a/51260097/2681283

HTH

**Comment by Darthfett** [comment]
If you're in refactor mode, make sure that the module that fails to import does not have any syntax errors.  I assumed that pylint was unable to find the module to import, but the error message was accurate, as I had a syntax error in the imported module.

**Comment by surajkj** [comment]
I was facing same issue.Resolved by below method
1) Select Interpreter command from the Command Palette (Ctrl+Shift+P)
2) Search for "Select Interpreter"
3) Select the installed python directory

Ref:- https://code.visualstudio.com/docs/python/environments#_select-an-environment

**Comment by drjonesy** [comment]
**[POSSIBLE SOLUTION]** Mac OSX

I initially thought it was the interpreter and this is partially true. If you ran `pip install Flask` and it installed. Then it might have installed into the Python 2 environment. If you are like me and need it for Python 3. Then try the following:

1. In the Terminal make sure you upgrade pip for Python3
```bash 
sudo python3 -m pip install --upgrade pip
```
2. You will be prompted to type in your password.
3. Once pip for Python3 is upgraded type:
```bash
sudo python3 -m pip install Flask
```
4. You may be prompted again for your admin password.

Once it is installed, simply make sure you are using the Python3 interpreter in VSCode.
At the top of your file add some white space and save. The red underline should disappear.

Hope this helps someone.

**Comment by Luksys5** [comment]
Solution for me was to set environment local by
        py -3 -m venv env

And to add python code under src folder
