### ISSUE TITLE
Go To Definition stops going to another file and only goes to import

### ISSUE THREAD

**Issue by joshpeng** [DonJayamanne/pythonVSCode#404]
VS Code: v1.6.1
Python extension: v0.5.0
Python install: v2.7.12
Windows 7 x64

When you launch VS Code, it seems to allow you to F12 Go-To-Definition accurately from file A into file B for a few seconds. After a little bit though, it stops working and only sends you to the import. Restarting VS Code restores the F12 capability, but only for a few seconds.

Test Files: [even_tree.zip](https://drive.google.com/file/d/0BwrhXZzVT5TYV1VERVpfd0pJRFE/view?usp=sharing)

1. Start VS Code
2. Open `even_tree_tests.py` from the `tests` folder and select `Tree` on line 7.
3. Press F12 --> opens `even_tree.py` and shows the `Tree` class on line 1.
4. Close `even_tree.py` and keep trying F12. After a few successes it will stop opening `even_tree.py` and start sending me to the import in `even_tree_tests.py` in line 2

**Comment by DonJayamanne** [comment]
Unfortunately this is a case of relative import. I'm surprised it works at times. It shouldn't work, this is because Jedi doesn't support it.
The only way you can get this working is to tell VS Code that you want auto complete to look for files in a specific location. Ideally you code won't work, as python won't know where the files are located, it will look for the packages relative to the current file.

_**note: this only applies to relative imports**_

Here's a modified version of the ```settings.json``` (workspace configuration) file
```json
"python.autoComplete.extraPaths": [
    "${workspaceRoot}/event_tree"
]
```

**Comment by joshpeng** [comment]
Huh. http://jedi.jedidjah.ch/en/latest/docs/features.html#supported-python-features
But in the middle of the supported features list is the item "relative imports"

**Comment by joshpeng** [comment]
For anyone running into this in the future, turns out there is some eccentric behavior with folders and imports having the same name on [Jedi#773](https://github.com/davidhalter/jedi/issues/773).

If you have...
```
$tree
.
├── a
    ├──__init__.py
    ├──a.py
    ├──c.py
└── b
    ├── __init__.py
    ├── b.py
```
In b.py, autocomplete won't work on `from a.a import A`, but it will work on `from a.c import C`

Note: Adding extraPaths as suggested above does not resolve `from a.a import A`.
