### ISSUE TITLE
nosetestArgs options ineffective

### ISSUE THREAD

**Issue by joshpeng** [DonJayamanne/pythonVSCode#407]
I tried putting
```
"python.unitTest.nosetestArgs": [
        "--stop"
    ]
```
inside user/workspace settings. Couldn't get it to run my nose tests with this argument though. I want the tests to terminate after the first fail, but they are still running the full set to completion before terminating.

1. Create two tests
2. Purposely make first test fail
3. Run all nose tests --> it runs both tests instead of terminating after first test. Args don't seem to be effective

Another issue. Documentation: https://github.com/DonJayamanne/pythonVSCode/wiki/nose-Framework
Here the code snippet says `python.unitTest.noseTestArgs`, but inside VS Code's default preferences the option is `python.unitTest.nosetestArgs` with `nosetest` being fully lower cased. Not sure if options are case-sensitive, but believe they are.

**Comment by DonJayamanne** [comment]
@joshpeng 
lol, copy past bug and lack of unittests. I only wrote unitests for the unittest framework and not for pytest and nosetest.
The problem is the code is looking at the parameters in ```settings.unitTest.pyTestArgs```

My suggestion, untill the next version is released, add the settings in both places.
This way when i release the next fix (definitely next week), it will work without any issues.

**Comment by DonJayamanne** [comment]
So, try adding the configuration as follows (temporary solution, till next build):
```json
"python.unitTest.nosetestArgs": [
        "--stop"
    ]
,"python.unitTest. pyTestArgs": [
        "--stop"
    ]
```

Published a build early today, will publish one with these fixes next week.
