### ISSUE TITLE
django ORM objects Autocomplete/Intellisense: Book.objects.filter Intellisense tips don't show

### ISSUE THREAD

**Issue by coladou** [DonJayamanne/pythonVSCode#422]
Autocomplete/Intellisense:      Book.objects.filter
Intellisense tips don't show

**Comment by DonJayamanne** [comment]
Unfortunately this isn't supported and isn't planned at this stage. Sorry

**Comment by coladou** [comment]
WTF...

**Comment by DonJayamanne** [comment]
@coladou , sorry, but I'm not sure my comments deserved such a remark.
This is not an easy feature to implement and as mentioned it isn't planned at this stage.
>Intellisense tips don't show

The answer to this was exactly what I provided.
Such comments are not helpful in any manner.

**Comment by DonJayamanne** [comment]
Apologies for closing this prematurely, I believe I misunderstood the issue. That's my fault. Please provide more information.
Please note Jedi library is being used for intellisense, hence it auto complete doesn't work under certain circumstances then this is possibly due to a limitation of the [jedi library](http://jedi.jedidjah.ch/en/latest/).
