### ISSUE TITLE
Extension not updating nor installing (if behind proxy/firewall)

### ISSUE THREAD

**Issue by volium** [DonJayamanne/pythonVSCode#511]
## Environment data
VS Code version:  1.7.1
Python Extension version:  0.5.1
Python Version:   2.7.x
OS and version:    Windows 7 (64-bit)

## Actual behavior
I tried updating extension from 0.5.1 to 0.5.2 and it was just sitting there, assuming it could be an issue with the update, I uninstalled the extension, and tried installing it from scratch, now 0.5.2 shows up in the extensions list, and when I click install.... nothing, it just sits there, doing nothing?

I've re-launched VS Code, restarted my computer, nothing seems to work. I tried installing other extension, and that DOES work fine.

When I updated from 0.5.0 to 0.5.1, it  took me a few tries as well, I had to re-launch VS Code, because it simply would not update, eventually, it did, though. 0.5.2 on the other hand? So far, no luck, still waiting for it to install after 15/20/30 mins? Who knows? Funny things is now I'm dependent on the extension to do some of my work.... (sigh)

## Expected  behavior
It should just install, right? After a few seconds, max.

## Steps to reproduce:  
-  Try installing 0.5.2, or updating from 0.5.1

**Comment by volium** [comment]
I was able to installer after connecting directly to the internet via Hotspot on my phone, which makes me believe this is an issue with our proxy/firewall. However, that does raise the question why other extensions work without issues?

**Comment by DonJayamanne** [comment]
Unfortunately you will have to check this with your work place and try to find out why the extension is being blocked. Possible due to file size or similar. 

You could however try installing it manually as follows:. 
Download the following file and following the instructions:. 
- Download link:. https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/python/0.5.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true  - Instructions Link:  https://code.visualstudio.com/Docs/extensions/install-extension#_install-a-packaged-extension-vsix

**Comment by DonJayamanne** [comment]
Oh yes, please change the version in the above link to 0.5.2

**Comment by volium** [comment]
Thanks for your suggestion, I'll give a  shot if/when the next update comes around. By the way, thank you for such an excellent plugin, it truly makes my daily job so much better! I enjoy VSCode so much in part because of your extension, keep up the awesome work.
