### ISSUE TITLE
Debug function is not always working

### ISSUE THREAD

**Issue by ladevan** [DonJayamanne/pythonVSCode#549]
## Environment data
VS Code version:  1.7.2
Python Extension version:  0.5.3
Python Version:   3.5.2
OS and version:   Windows 8.1 
Your launch.json (if dealing with debugger issues):  
```
"version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config.python.pythonPath}",
            "program": "${file}",
            "console": "integratedTerminal",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        }
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

## Actual behavior
Seems like sometimes the debug/start without debug function is not working. After I press "F5" or "Ctrl+F5", nothing happens. Or run from "command pallete", then it shows ` 'Debug: Start Debugging' is not enabled in the current context`
## Expected  behavior
Start Debug(F5) and Start Without Debug(Ctrl+F5) works all the time
## Steps to reproduce:  
-  
-

**Comment by DonJayamanne** [comment]
Please could you try debugging a simple Python file:

```pyton
a = 1
b = 2
c = a + b
print(c)
```

Let me know how this goes.
Please check if there are any errors in the error console (```Help->Toggle Developer Tools)

**Comment by ladevan** [comment]
Hi Don, thanks for your quick response.

I tried the simple python file. When `F5/Ctrl+F5` didn't work, I didn't see any error message in console. But one interesting thing I found out is that, seems like `F5` will always work, but after I triggered once `Ctrl+F5`, both `F5` and `Ctrl+F5` didn't work. I have to click the `debug` button in debug panel to do debugging, then `F5` will work again, and `Ctrl+F5` will work once, but again won't work after that.

During this process, I didn't see any error message.

**Comment by fj128** [comment]
I have the same problem and I think I see what's going wrong.

When I press F5, then debugging starts, status line color changes to orange, and the floating bar with debugger buttons appears. When I press F5 again, program resumes execution, terminates, VSCode exits debug mode. This can be repeated indefinitely, everything works fine. If I have `"stopOnEntry": false`, pressing F5 works exactly the same, except the program resumes immediately and runs to termination.

However! If I use ctrl-F5, then status line color doesn't change, the floating debug bar doesn't appear, the program prints its "Hello, world" in the Debug Console and terminates, but neither F5 nor ctrl-F5 work any more.

If __after that__ I click the debug button with a mouse, then debugger starts, runs the program to termination (automatically or after I press F5 again, depending on the stopOnEntry setting), but _doesn't exit the debug mode_. After I manually exit the debug mode by clicking "Stop" button, VSCode returns back to the normal state where I can run program with F5 repeatedly.

So, the problem appears to be that `workbench.action.debug.run` is not the same as `workbench.action.debug.start` with `"stopOnEntry": false`, and is currently bugged: it doesn't properly enter debug mode, so it's not properly exited, so some part of VSCode keeps thinking that debug mode is active (which persists into the next debugging session even) and doesn't allow to start it again with keyboard shortcuts. Using mouse however gets through somehow and allows to get back to the sane state.

__Temporary workaround:__ use `"stopOnEntry": false` and F5 to run scripts if you want ctrl-F5-like functionality. If you accidentally press ctrl-F5, get back to functional state by using the mouse to run and terminate your program once. Or unbind ctrl-F5 until this bug is fixed.

**Comment by fj128** [comment]
On a related note, with `"stopOnEntry": false`, the breakpoint on the first (non-empty, non-comment) line of code doesn't work, lol. I guess I know how it's implemented =). This is what I get after pressing F5 once:

![image of what I get](http://i.imgur.com/EZKSqgr.png)

**Comment by ladevan** [comment]
Thank you, @fj128. That's exactly what I found also. I will use `"stopOnEntry":false` for now.
