### ISSUE TITLE
Autodesk Maya debugging Problems

### ISSUE THREAD

**Issue by asierralozano** [DonJayamanne/pythonVSCode#690]
## Environment data
VS Code version:  1.8.1
Python Extension version:  0.5.6
Python Version:   2.7
OS and version:    Windows 10

## Actual behavior

Trying to do some Debugging with Maya. The problem is that the debugger is obviating the breakpoints. They turns grey, and it looks like the debugger is not taking into account all breakpoints that i set

## Expected  behavior

Stop in the Breakpoints

## Steps to reproduce:  
-  Open AutoDesk Maya 2015
-  Open ScriptEditor in Maya and execute this piece of code:

sys.path.append(r"C:\Python27\Lib\site-packages")
import ptvsd
ptvsd.enable_attach("my_secret", address = ('127.0.0.1', 3000))

-  Set some breakpoints in the code and call the function in Maya

## Settings  
Your launch.json (if dealing with debugger issues):  
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Maya",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "F:/Programacion/AutoRig",
            "port": 3000,
            "secret": "my_secret",
            "host":"localhost"
        }     
    ]
}
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by asierralozano** [comment]
Any though about this? Im a little bit frustated with this :(

**Comment by DonJayamanne** [comment]
Is this remote debugging or just local debugging?

**Comment by asierralozano** [comment]
Autodesk Maya is in the same computer of the script that i want to debug, but i need to open ports to comunicate, so it is supossed to be remote.

Thanks for answering DonJayamanne!

**Comment by asierralozano** [comment]
Probably is because a new update of the python extension, but right now it is working. 

If other people want to debug a plugin in Autodesk Maya, just run the Attach Profile of the debugger in Visual Studio and run your plugin in Maya :)

Thanks @DonJayamanne  for this amazing extension!

**Comment by PGui** [comment]
Hi @DonJayamanne ,

I allow myself to answer this thread because I have the same issue described above.
I followed [**this tutorial**](http://iwonderwhatjoeisworkingon.blogspot.fr/2017/04/debugging-maya-using-visual-studio-code.html) to be able to debug my maya scripts within VSCode, but without success so far.
As you can see in the comment section of the page, other people have the same breakpoint issue.

In my case, the maya-vscode connection works since I can see the log of my scripts launched from maya in the VSCode output.

I'm using Maya 2018, VSCode 1.16.1, pythonVSCode 0.7.0 and ptvsd 3.0.0.

I hope there is a solution, using maya with vscode seems to be the most practical solution I found online.

Thanks

P.S: I'm sorry if I'm not at the right place to write this comment, maybe you want me to create a new issue ?

**Comment by asierralozano** [comment]
To be honest, I don't know how, but now it works. If you need some help, just let me know, and I will help you :)
