### ISSUE TITLE
configure pylint executable location

### ISSUE THREAD

**Issue by gbritton1** [DonJayamanne/pythonVSCode#766]
## Environment data
VS Code version:  1.91
Python Extension version:  0.58
Python Version:   3.6
OS and version:    Windos 7-64 SP1

I specify my path to Python in the launch.json like this:

"pythonPath": "${config.python.pythonPath}",

where "pythonPath" is defined in my user settings.json like this:

"python.pythonPath": "C:/Program Files (x86)/Python36-32/python.exe",

Since my linters hang off the same directory, in the Scripts subdirectory, I'd like to be able to do something like this in settings.json:

"python.linting.pylintPath": "${config.python.pythonPath}/../Scripts/pylint.exe",

But when I do that I get an error message when trying to do linting, saying that it can't find the linter.

Is it possible to concatenate the config reference (the ${...} part) with the rest of the path?
If so, what is the proper syntax?

**Comment by DonJayamanne** [comment]
Will fix this, however I strongly suggest not going down this path.
The problem is that if you use a module that is installed in the environment ```C:/Program Files (x86)/Python36-32/python.exe```, and Pylint is installed somewhere else, then pylint will complain about not being able to import some modules.

This would happen because the modules are installed in the python environment defined in ```python.pythonPath```, but pylint is pointing to some other python environment.

I.e. you could end up with plenty of warnings/errors from Pylint about not being able to import modules

**Comment by gbritton1** [comment]
Thanks for the fix, though I don't understand your concerns.  The whole point of the request is for when pylint is installed in the default location by pip, which by default is the Scripts directory.  If I had forced an installation to some other location, I would not have made the request. (Indeed, in such a case the request would not make sense.)
