### ISSUE TITLE
Go to symbol in workspace leads to nonexisting files

### ISSUE THREAD

**Issue by oleynikandrey** [DonJayamanne/pythonVSCode#829]
## Environment data
VS Code version:  1.10.2
Python Extension version: 0.6.0 
Python Version: python 3.6.0
OS and version: Windows 10 x64

## Steps to reproduce:  
- Open a directory with files
- Click Ctrl + T and look at list of found symbols - paths to files in witch these symbols are found are incorrect.

<img width="489" alt="code_2017-03-16_19-46-08" src="https://cloud.githubusercontent.com/assets/1157958/24035594/47abeb08-0b07-11e7-9ab5-ee30590e91ec.png">

## Settings  
Your settings.json:   
```
{
    "editor.cursorStyle": "block",
    "vim.useSystemClipboard": true,
    "window.zoomLevel": 0,
    "python.pythonPath": "C:/Python36/python.exe",
    "python.linting.pep8Enabled": true,
    "python.linting.pylintArgs": ["--disable=C0111", "--max-line-length=120"],
    //"python.linting.pep8Args": ["--max-line-length=120"],
    "terminal.integrated.fontFamily": "Source Code Pro for Powerline",
    "terminal.integrated.fontSize": 13,
    "files.autoSave": "off",
    "editor.minimap.enabled": true
}
```   
## Logs
Output from ```Python``` output panel  
```
----------Generating Tags----------
ctags --options=C:\Users\user\.vscode\extensions\donjayamanne.python-0.6.0\resources\ctagOptions --languages=Python --exclude=**/site-packages/** -o c:\Users\user\repoes\temp\temp_project/.vscode/tags .
```

**Comment by olipratt** [comment]
I've just hit this problem on my Windows 10 machine too, and found a workaround.

The problem seems to be in the path provided to `ctags` by the plugin - in particular the `/.vscode/tags` part using Linux-style path separators. With this format, the tags in the tag file are not paths relative to the location of the tag file, but instead seem to be relative to the parent directory of the workspace root for whatever reason.

Changing the setting for where the file should be stored to use windows-style path separators makes this work fine, and the paths in the tag file are indeed then relative to the tag file's path:

```
    "python.workspaceSymbols.tagFilePath": "${workspaceRoot}\\.vscode\\tags"
```

That works as a workaround - but is there some way you can make the default settings use the right path separators for the OS VSCode is running on?
