### ISSUE TITLE
Switching Interpreter should also change terminal environment

### ISSUE THREAD

**Issue by chrmarti** [DonJayamanne/pythonVSCode#864]
_From @LordAmit on April 7, 2017 7:29_

- VSCode Version: Version 1.11.1
- OS Version: Kubuntu 16.10

Steps to Reproduce:

1. `F1`, 
2. `Python: Choose workspace interpreter`
3. Select desired interpreter
4. Use integrated terminal to execute a command (like `python filename.py`)
5. Since Ubuntu still uses python2 by default, get syntax errors

_Copied from original issue: Microsoft/vscode#24183_

**Comment by LordAmit** [comment]
Thanks for moving! Didn't realize it was related to extension. 

Sorry for the trouble.

**Comment by DonJayamanne** [comment]
@LordAmit , unfortunately this isn't an extension issue.  
The problem is simple, when selecting the ```Work space interpreter``` you're merely telling the Python extension what Interpreter needs to be used when working on the current workspace.   
However, when you open a terminal window (in VS Code) it has no idea what interpreter has been configured, in fact it is using a completely separate environment, thats isolated from the extension.  

I'll do some more research, but it doesn't look promising.
