### ISSUE TITLE
ImportError: Cannot find local modules in workspace

### ISSUE THREAD

**Issue by mtham8** [DonJayamanne/pythonVSCode#920]
The internal terminal can identify which pip and python version I'm using and modules that I've pip installed. However, for files that are imported from local directories in the same workspace -- pythonVSCode cannot find them. Any advice to solve this problem? I've searched everywhere and no dice. 

## Environment data
VS Code version:  Version 1.11.2 (1.11.2)
Python Extension version:  Version 0.6.3
Python Version:   2.7
OS and version:   mac os sierra

## Actual behavior
`ImportError: No module named main_insight.base_insight`

## Expected  behavior
runs file in terminal

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
  {
      "name": "Python",
      "type": "python",
      "request": "launch",
      "stopOnEntry": false,
      "pythonPath": "${config:python.pythonPath}",
      "program": "${file}",
      "cwd": "${workspaceRoot}",
      "env": {
        "PYTHONPATH": "${workspaceRoot}"
      },
      "envFile": "${workspaceRoot}/.env",
      "debugOptions": [
        "WaitOnAbnormalExit",
        "WaitOnNormalExit",
        "RedirectOutput"
      ]
    },
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
 $ /usr/bin/python2.7 /Users/main_insight/yearly_yearly_energy_report_insight/runner.py
Traceback (most recent call last):
  File "/Users/main_insight/yearly_yearly_energy_report_insight/runner.py", line 3, in <module>
    from main_insight.base_insight import BaseRunner
ImportError: No module named main_insight.base_insight
```

**Comment by DonJayamanne** [comment]
Please could you provide me with the sample code along with the folder structure (better yet, why not zip the sample files and upload it).

**Comment by tamlhp** [comment]
Please fix this soon. We just want to import the local module where the original code is placed.

**Comment by gandhis1** [comment]
This issue doesn't make sense to me. Why do you expect it to be able to find those modules? Your launch working directory will always be your workspace root. However, your project is located in a subdirectory? You need to change the cwd parameter of your launch.json to your project directory. I believe there is a VS Code wild card which refers to ${file_dir} (or something similar). If you are referring to a module in a directory, then you need to have an __init__.py in that directory.

**Comment by tamlhp** [comment]
For example,
+ In data.py:
class ABC:
    def __init__():
        return

+ In main.py:
from data import ABC

+ Put these files in the same directory

+ Run python main.py --> normal
+ "Run cell" in VB code using Jupyter plugin --> error
ImportError: cannot import name 'ABC'

**Comment by gandhis1** [comment]
Your issue is legitimate, but is a different issue from the one that OP is talking about. He is discussing running a Python script in the output window using a launch configuration. You are talking about Jupyter.

The problem is that the jupyter startup folder is the workspace root. If your project is located in a sub-directory of your workspace root, then it will not work. You either need to change your workspace root, or change the setting below:

`"jupyter.notebook.startupFolder": "${workspaceRoot}",`

**Comment by tamlhp** [comment]
Thanks a lot,
But normally when I open the jupyter notebook in web browser, I can still do the import. It understands where the notebook is located. Maybe the plugin in VSCode should automatilly understand where the current file is located. That is, when click on "Run here", it asks "Open a new notebook", and that when it should automatically change the startupFolder.

**Comment by gandhis1** [comment]
That's because all your code is located in one file, the ipynb. Lets say you have a nested workspace with multiple folders and files. All your code is going to execute in the same Jupyter instance. Which directory should be the startup folder? It can't be changed ex post facto. Now you might argue why not all subdirectories in the current path? Well, then what if you have a conflict - two sub folders with the same file. For this reason, a workspace ought to be only a single project.
