### ISSUE TITLE
Lint Errors should be url

### ISSUE THREAD

**Issue by fordp2002** [DonJayamanne/pythonVSCode#983]
## Environment data
VS Code version:  
Python Extension version:  
Python Version:   
OS and version:    

## Actual behavior
A static pop-up error is generated from Lint
## Expected  behavior
A static pop-up error is generated from Lint that doubles as a URL e.g. http://pylint-messages.wikidot.com/messages:c0111
## Steps to reproduce:  
-  
-  

## Settings  
Your launch.json (if dealing with debugger issues):  
```json
```   
Your settings.json:   
```json
```   
## Logs
Output from ```Python``` output panel  
```
```   
Output from ```Console window``` (Help->Developer Tools menu)
```
```

**Comment by DonJayamanne** [comment]
What's this `A static pop-up error is generated from Lint` you are referring to.
Do you mean a pop up is displayed instead of the error messages?
Please could you provide a screen sample?

**Comment by fordp2002** [comment]
The pop-up LINT messages sometimes have a good description and sometimes do not.[
![lint](https://cloud.githubusercontent.com/assets/3258482/26571482/0f60c250-450e-11e7-9652-7b1609c2334d.jpg)
](url)
See the top line C0111. I am suggesting that line becomes a link to the website about that error.

**Comment by deronnax** [comment]
1. the errors messages you point the finger at do not come from PythonVSCode but from the code checking software used by PVSC under hood, [pycodestyle](https://github.com/PyCQA/pycodestyle)
2. the website you propose is not tied or affiliated to Python or pycodestyle in any way, so we can't rely on it (they can change the content, be shutdown, give up ownership, etc). Plus, the sudden amount of traffic that would result by linking to them in VSCode would probably trigger a shutdown since it' s hosted on a somewhat free hosting

But the idea is not bad. I see that pycodestyle offer a webpage to more comprehensive description of the errors : http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes. But should PythonVSCode do the linking itself, or should we ask pycodestyle's guys to build it in pycodestyle's ?

@DonJayamanne , what do you think ?

**Comment by fordp2002** [comment]
Thanks for considering my idea. I always get frustrate when I have to cross type or copy and paste something that the software could do for you. Thanks for this excellent tool.

Python is rapidly becoming my favourite language ever!
